import { type NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

import { api } from '~/utils/api'

interface TutorCardProps {
  name?: string
  description?: string
  productImageUrl?: string
  price?: number
  tutorId: string
}

const TutorCard = (props: TutorCardProps) => {
  const { name, description, productImageUrl, price, tutorId } = props

  return (
    <div className="mt-2 rounded bg-white shadow-lg shadow-gray-200 duration-300 hover:-translate-y-1 dark:bg-gray-800 dark:shadow-gray-900">
      <Link
        href={`/tutor/${encodeURIComponent(tutorId)}`}
        className="cursor-pointer"
      >
        <figure>
          <img
            src={productImageUrl}
            className="h-52 w-full rounded-t object-cover"
          />
          <figcaption className="p-4">
            <p className="mb-1 text-lg font-bold leading-relaxed text-gray-800 dark:text-gray-300">
              {name}
            </p>
            <small className="leading-5 text-gray-500 dark:text-gray-300">
              {description}
            </small>
            <p className="text-right text-lg font-bold leading-relaxed text-gray-800 dark:text-gray-300">
              S/ {price}/h
            </p>
          </figcaption>
        </figure>
      </Link>
    </div>
  )
}

const Home: NextPage = () => {
  const { data: tutors } = api.tutor.tutors.useQuery()

  if (!tutors) return null

  return (
    <>
      <Head>
        <title>TutorConnect</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gray-900">
        <section className="container mx-auto py-10 px-12">
          <div className="grid grid-flow-row gap-8 text-neutral-600 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {tutors.map((tutor) => (
              <TutorCard
                tutorId={tutor.id}
                key={tutor.id}
                name={tutor.firstName + ' ' + tutor.lastName}
                description={tutor.description}
                productImageUrl={tutor.productImageUrl}
                price={tutor.pricePerHour}
              />
            ))}
          </div>
        </section>
      </main>
    </>
  )
}

export default Home
